-- Generated by scripts/promote.ts on 2026-06-15T20:42:54.648Z
insert into public.snippets (id, domain, format, concept, text) values
('ai-context-windows', 'ai', 'theory', 'Context Windows', 'Context windows are a fundamental concept in natural language processing and refer to the amount of text considered when making predictions, allowing models to capture local relationships and dependencies between words, which is essential for understanding language syntax and semantics.'),
('ai-vector-databases', 'ai', 'theory', 'Vector Databases', 'Vector databases are specialized indexes that enable efficient similarity searches and nearest neighbor queries on high dimensional vector data, commonly used in artificial intelligence and machine learning applications, such as image and text embeddings.'),
('ai-agent-tool-calling', 'ai', 'theory', 'Agent Tool Calling', 'Agent tool calling refers to the process of invoking external tools or services from within an artificial intelligence or machine learning agent to leverage specific capabilities or expertise, enabling more effective problem solving and decision making.'),
('st-law-of-large-numbers', 'stats', 'theory', 'Law of Large Numbers', 'The Law of Large Numbers states that as the number of trials increases, the average of the results will converge to the expected value, which is a fundamental concept in statistics and probability theory.'),
('st-bootstrap-resampling', 'stats', 'theory', 'Bootstrap Resampling', 'Bootstrap resampling is a statistical technique that involves creating multiple datasets from an original dataset by randomly sampling with replacement, allowing researchers to estimate the variability of a statistic or model by analyzing the distribution of results across these resampled datasets.'),
('st-simpson-s-paradox', 'stats', 'theory', 'Simpson''s Paradox', 'Simpson''s Paradox occurs when a trend appears in several different groups of data but disappears or reverses when the groups are combined, due to confounding variables, leading to incorrect conclusions about the relationship between variables.'),
('st-type-i-vs-type-ii-errors', 'stats', 'interview', 'Type I vs Type II Errors', 'I would define Type I and Type II errors as two types of mistakes in statistical hypothesis testing, where I would say a Type I error occurs when a true null hypothesis is incorrectly rejected, and a Type II error occurs when a false null hypothesis is failed to be rejected.'),
('st-when-to-use-median-over-mean', 'stats', 'interview', 'When to Use Median over Mean', 'I would use median over mean when dealing with skewed distributions or outliers, as the median is more robust and better represents the central tendency in such cases, whereas the mean is sensitive to extreme values and can be misleading.'),
('st-explaining-statistical-power', 'stats', 'interview', 'Explaining Statistical Power', 'I would define statistical power as the probability of correctly rejecting a false null hypothesis, which is crucial in hypothesis testing, and it depends on factors like sample size, effect size, and significance level, so I would carefully consider these elements when designing experiments to ensure adequate power.'),
('ml-k-means-clustering', 'ml', 'theory', 'K-Means Clustering', 'K-Means Clustering is a type of unsupervised learning algorithm that partitions the data into K clusters based on their similarities, where K is a predefined number, and each cluster is represented by a centroid, with the goal of minimizing the sum of squared distances between each point and its closest centroid.'),
('ml-feature-selection-strategy', 'ml', 'interview', 'Feature Selection Strategy', 'I would approach feature selection strategy by first understanding the problem and data, then applying techniques like correlation analysis and recursive feature elimination to identify relevant features, and finally evaluating their impact on model performance using cross-validation.'),
('ml-choosing-evaluation-metrics', 'ml', 'interview', 'Choosing Evaluation Metrics', 'I would choose evaluation metrics based on the problem type, considering metrics like accuracy, precision, recall, and F1 score for classification, and mean squared error or R squared for regression, to get a comprehensive understanding of my model''s performance.'),
('ml-explaining-a-model-to-stakehol', 'ml', 'interview', 'Explaining a Model to Stakeholders', 'I would explain a model to stakeholders by starting with the problem we are trying to solve and the goals of the project, then walking them through the data used to train the model, the type of algorithm used, and the key performance metrics, emphasizing how the model works and what insights it provides.'),
('ml-cross-validation-with-cross-va', 'ml', 'python', 'Cross Validation with cross_val_score', 'from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.svm import SVC
iris = load_iris()
X = iris.data
y = iris.target
svc = SVC(kernel=''linear'', C=1)
scores = cross_val_score(svc, X, y, cv=5)
print(scores)'),
('ml-confusion-matrix-and-classific', 'ml', 'python', 'Confusion Matrix and Classification Report', 'from sklearn.metrics import confusion_matrix, classification_report
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))'),
('ai-reducing-hallucinations', 'ai', 'interview', 'Reducing Hallucinations', 'I would approach reducing hallucinations in AI models by understanding the differences between hallucinations and true predictions, then implementing techniques like data preprocessing, regularization, and uncertainty estimation to mitigate them.'),
('ai-evaluating-llm-outputs', 'ai', 'interview', 'Evaluating LLM Outputs', 'I would evaluate LLM outputs by assessing their accuracy and relevance to the task at hand, considering factors such as context, bias, and uncertainty, to ensure the model is generating reliable and informative responses.'),
('co-hash-map-frequency-count', 'coding', 'python', 'Hash Map Frequency Count', 'def hash_map_frequency_count(words):
    frequency_count = {}
    for word in words:
        if word in frequency_count:
            frequency_count[word] += 1
        else:
            frequency_count[word] = 1
    return frequency_count'),
('co-list-comprehensions', 'coding', 'python', 'List Comprehensions', 'numbers = [1, 2, 3, 4, 5]
squared_numbers = [n ** 2 for n in numbers]
print(squared_numbers)
numbers = [1, 2, 3, 4, 5]
even_numbers = [n for n in numbers if n % 2 == 0]
print(even_numbers)'),
('co-reading-csv-with-pandas', 'coding', 'python', 'Reading CSV with Pandas', 'import pandas as pd

data = pd.read_csv(''data.csv'')
print(data.head())
print(data.info())
print(data.describe())'),
('co-self-joins', 'coding', 'sql', 'Self Joins', 'SELECT e1.employee_id, e1.name, e2.manager_id
FROM employees e1
JOIN employees e2
ON e1.manager_id = e2.employee_id;'),
('co-date-truncation-and-grouping', 'coding', 'sql', 'Date Truncation and Grouping', 'SELECT DATE_TRUNC(''day'', order_date) AS order_day, SUM(order_total) AS total_sales
FROM orders
GROUP BY order_day
ORDER BY order_day;'),
('co-deduplication-with-row-number', 'coding', 'sql', 'Deduplication with ROW_NUMBER', 'SELECT employee_id, name, email
FROM (
  SELECT employee_id, name, email,
         ROW_NUMBER() OVER (PARTITION BY email ORDER BY employee_id) AS row_num
  FROM employees
) AS subquery
WHERE row_num = 1')
on conflict (id) do update set
  domain = excluded.domain,
  format = excluded.format,
  concept = excluded.concept,
  text = excluded.text;
