/**
 * Promotes approved candidates to SQL for Supabase.
 *
 * Usage: npx tsx scripts/promote.ts
 * Reads content/candidates.json, takes everything with status "approved",
 * writes supabase/seed_generated.sql (upsert), and marks them "promoted".
 * Paste the SQL into the Supabase SQL Editor. The app loads snippets from
 * the DB, so new content goes live without redeploying the frontend.
 */
import { readFileSync, writeFileSync } from "fs";

interface Candidate {
  id: string;
  domain: string;
  format: string;
  concept: string;
  text: string;
  status: string;
}

const path = "content/candidates.json";
const candidates: Candidate[] = JSON.parse(readFileSync(path, "utf-8"));
const approved = candidates.filter((c) => c.status === "approved");

if (approved.length === 0) {
  console.log('Nothing approved. Edit content/candidates.json and set status to "approved" on the good ones.');
  process.exit(0);
}

const esc = (s: string) => s.replace(/'/g, "''");
const values = approved
  .map((c) => `('${c.id}', '${c.domain}', '${c.format}', '${esc(c.concept)}', '${esc(c.text)}')`)
  .join(",\n");

const sql = `-- Generated by scripts/promote.ts on ${new Date().toISOString()}
insert into public.snippets (id, domain, format, concept, text) values
${values}
on conflict (id) do update set
  domain = excluded.domain,
  format = excluded.format,
  concept = excluded.concept,
  text = excluded.text;
`;

writeFileSync("supabase/seed_generated.sql", sql);
for (const c of approved) c.status = "promoted";
writeFileSync(path, JSON.stringify(candidates, null, 2));

console.log(`Wrote ${approved.length} snippets to supabase/seed_generated.sql`);
console.log("Paste it into the Supabase SQL Editor and run it. Snippets go live instantly.");
